"""Add price field to Coupon model

Revision ID: 088d3d99e2a9
Revises: e126b8a0d0b8
Create Date: 2025-07-16 16:14:59.786958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088d3d99e2a9'
down_revision = 'e126b8a0d0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False, server_default="0.0"))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
