"""added coupon_purchase

Revision ID: 31a52a43fae3
Revises: 088d3d99e2a9
Create Date: 2025-07-18 19:35:27.951263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a52a43fae3'
down_revision = '088d3d99e2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('redeemed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('redeemed')
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###
