"""Added coupon_id, vendor_id, status, redemption_code to Coupon

Revision ID: 5748c7523806
Revises: cf1bf87a7287
Create Date: 2025-07-06 14:35:14.508422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5748c7523806'
down_revision = 'cf1bf87a7287'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_id', sa.String(length=50), nullable=True))  # ✅ set nullable
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('redemption_code', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint("uq_coupon_coupon_id", ['coupon_id'])  # ✅ named constraint


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('redemption_code')
        batch_op.drop_column('status')
        batch_op.drop_column('vendor_id')
        batch_op.drop_column('coupon_id')

    # ### end Alembic commands ###
