"""Add category to coupon

Revision ID: e126b8a0d0b8
Revises: 5bc4e52d573f
Create Date: 2025-07-08 13:17:06.000501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e126b8a0d0b8'
down_revision = '5bc4e52d573f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False, server_default='Uncategorized'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
