"""fix FK constraint and add location

Revision ID: ebf709f09767
Revises: f68235f1aa0f
Create Date: 2025-07-21 18:02:56.542037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf709f09767'
down_revision = 'f68235f1aa0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_coupon_vendor_id', 'vendor', ['vendor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_constraint('fk_coupon_vendor_id', type_='foreignkey')

    # ### end Alembic commands ###
